/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DATA.Conexion;

/**
 *
 * @author desarrollo
 */
public class FrmApp extends javax.swing.JFrame {

    /**
     * Creates new form FrmApp
     */
    IFrmInsert frmInsertar=new IFrmInsert();
    IFrmListar frmListar=new IFrmListar();
    IFrmModificarEliminar frmModificar=new IFrmModificarEliminar();
    public FrmApp() {
        initComponents();
        Conexion.conectar();
        this.add(frmInsertar);
        this.add(frmListar);
        this.add(frmModificar);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItmInsert = new javax.swing.JMenuItem();
        mnuItmSelect = new javax.swing.JMenuItem();
        mnuItmUpdate = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuItmCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenedor");

        jMenu1.setText("Alumno");

        mnuItmInsert.setText("Ingresar");
        mnuItmInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmInsertActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItmInsert);

        mnuItmSelect.setText("Listar");
        mnuItmSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmSelectActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItmSelect);

        mnuItmUpdate.setText("Modificar/Eliminar");
        mnuItmUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmUpdateActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItmUpdate);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        mnuItmCerrar.setText("Cerrar");
        mnuItmCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItmCerrarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItmCerrar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItmInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmInsertActionPerformed
        frmInsertar.show();
    }//GEN-LAST:event_mnuItmInsertActionPerformed

    private void mnuItmSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmSelectActionPerformed
        frmListar.show();
    }//GEN-LAST:event_mnuItmSelectActionPerformed

    private void mnuItmCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItmCerrarActionPerformed

    private void mnuItmUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItmUpdateActionPerformed
        frmModificar.show();
    }//GEN-LAST:event_mnuItmUpdateActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuItmCerrar;
    private javax.swing.JMenuItem mnuItmInsert;
    private javax.swing.JMenuItem mnuItmSelect;
    private javax.swing.JMenuItem mnuItmUpdate;
    // End of variables declaration//GEN-END:variables
}
