/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author desarrollo
 */
import NEGOCIO.Alumno;
import GUI.*;
import DATA.*;
import java.sql.*;
import javax.swing.JOptionPane;
public class IFrmInsert extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmInsert
     */
    public IFrmInsert() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtIrut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        chkBecado = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox<>();
        rdbMasculino = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdbFemenino = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnLimpiarIngreso = new javax.swing.JButton();
        btnSalirIngreso = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Insertar Alumno");

        jLabel1.setText("Rut");

        jLabel3.setText("N° Alumno");

        chkBecado.setText("Becado");

        jLabel4.setText("Ciudad");

        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arica", "Antofagsta", "La Serena", "Viña Del Mar", "Santiago", "Valdivia" }));

        grpSexo.add(rdbMasculino);
        rdbMasculino.setSelected(true);
        rdbMasculino.setText("M");

        jLabel5.setText("Sexo");

        grpSexo.add(rdbFemenino);
        rdbFemenino.setText("F");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnInsert.setText("Guardar");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnLimpiarIngreso.setText("Limpiar");
        btnLimpiarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIngresoActionPerformed(evt);
            }
        });

        btnSalirIngreso.setText("Salir");
        btnSalirIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnInsert)
                .addGap(53, 53, 53)
                .addComponent(btnLimpiarIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnSalirIngreso)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnLimpiarIngreso)
                    .addComponent(btnSalirIngreso))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIrut, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chkBecado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbFemenino)
                                    .addComponent(rdbMasculino))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkBecado))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(rdbMasculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbFemenino)
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        guardarAlumno();  
        limpiar();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnLimpiarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIngresoActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarIngresoActionPerformed

    private void btnSalirIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirIngresoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirIngresoActionPerformed
    public void limpiar(){
        
        this.txtIrut.setText(null);
        this.txtNumero.setText(null);
        this.txtIrut.requestFocus();
        this.cmbCiudad.setSelectedIndex(0);
        this.chkBecado.setSelected(false);
        this.rdbMasculino.setSelected(true);
    }
    public void guardarAlumno() {
        String rut=txtIrut.getText();
        
        
        int numero=Integer.parseInt(txtNumero.getText());
        boolean beca=chkBecado.isSelected();
        String ciudad=(String)cmbCiudad.getSelectedItem();
        char sexo;
        if (rdbFemenino.isSelected()) {
            sexo=rdbFemenino.getText().charAt(0);
        } else {
            sexo=rdbMasculino.getText().charAt(0);
        }
        Alumno objAlu=new Alumno(rut, numero, beca,ciudad,sexo);
        objAlu.insertar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLimpiarIngreso;
    private javax.swing.JButton btnSalirIngreso;
    private javax.swing.JCheckBox chkBecado;
    private javax.swing.JComboBox<String> cmbCiudad;
    private javax.swing.ButtonGroup grpSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdbFemenino;
    private javax.swing.JRadioButton rdbMasculino;
    private javax.swing.JTextField txtIrut;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
