/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NEGOCIO.Alumno;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author desarrollo
 */
public class IFrmModificarEliminar extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmModificar
     */
    public IFrmModificarEliminar() {
        initComponents();
        pnlDatos.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSexoMod = new javax.swing.ButtonGroup();
        txtRutBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarRut = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumMod = new javax.swing.JTextField();
        chkBecadoMod = new javax.swing.JCheckBox();
        cmbCiudadMod = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rdbMasculinoMod = new javax.swing.JRadioButton();
        rdbFemeninoMod = new javax.swing.JRadioButton();
        btnMod = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Modificar y Eliminar Alumno");

        jLabel1.setText("Rut");

        btnBuscarRut.setText("Buscar");
        btnBuscarRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRutActionPerformed(evt);
            }
        });

        pnlDatos.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setText("N° ");

        chkBecadoMod.setText("Becado");

        cmbCiudadMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arica", "Antofagsta", "La Serena", "Viña Del Mar", "Santiago", "Valdivia" }));

        jLabel3.setText("Sexo");

        grpSexoMod.add(rdbMasculinoMod);
        rdbMasculinoMod.setText("M");

        grpSexoMod.add(rdbFemeninoMod);
        rdbFemeninoMod.setText("F");

        btnMod.setText("Actualizar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMod))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addComponent(chkBecadoMod)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(rdbMasculinoMod)
                                .addGap(18, 18, 18)
                                .addComponent(rdbFemeninoMod))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumMod, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCiudadMod, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCiudadMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkBecadoMod)
                    .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(rdbMasculinoMod)
                        .addComponent(rdbFemeninoMod)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMod)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtRutBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnBuscarRut)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscarRut))
                .addGap(18, 18, 18)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cargarAlumno(){
        try {
            Alumno objAlu=new Alumno();
            objAlu.setRut(txtRutBuscar.getText());
            ResultSet res=objAlu.cargarRut();
            if (res.next()) {
                JOptionPane.showMessageDialog(null, "Alumno existe");
                txtRutBuscar.setEditable(false);
                pnlDatos.setVisible(true);
                txtNumMod.setText(res.getString(2));
                if (res.getString(3).equals("1")) {
                    chkBecadoMod.setSelected(true);
                } else {
                    chkBecadoMod.setSelected(false);
                }
                cmbCiudadMod.setSelectedItem(res.getString(4));
                if (res.getString(5).equals(rdbMasculinoMod.getText())) {
                    rdbMasculinoMod.setSelected(true);
                } else {
                    rdbFemeninoMod.setSelected(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No existe alumno");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    private void btnBuscarRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRutActionPerformed
        cargarAlumno();
    }//GEN-LAST:event_btnBuscarRutActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        actualizarAlumno();
    }//GEN-LAST:event_btnModActionPerformed
    public void eliminarAlumno(){
        try {
            String rut=txtRutBuscar.getText();
            
            Alumno objAlu=new Alumno(rut);
            objAlu.eliminarAlumno();
            limpiarModificacion();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarAlumno();
    }//GEN-LAST:event_btnEliminarActionPerformed
    public void actualizarAlumno(){
        try {
            String rut=txtRutBuscar.getText();
            int numero=Integer.parseInt(txtNumMod.getText());
            boolean beca=chkBecadoMod.isSelected();
            String ciudad=(String)cmbCiudadMod.getSelectedItem();
            char sexo;
            if (rdbFemeninoMod.isSelected()) {
                sexo=rdbFemeninoMod.getText().charAt(0);
            } else {
                sexo=rdbMasculinoMod.getText().charAt(0);
            }
            Alumno objAlu=new Alumno(rut, numero, beca,ciudad,sexo);
            objAlu.actualizar();
            limpiarModificacion();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    public void limpiarModificacion(){
        pnlDatos.setVisible(false);
        txtRutBuscar.setEditable(true);
        txtRutBuscar.setText(null);
        txtRutBuscar.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRut;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMod;
    private javax.swing.JCheckBox chkBecadoMod;
    private javax.swing.JComboBox<String> cmbCiudadMod;
    private javax.swing.ButtonGroup grpSexoMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JRadioButton rdbFemeninoMod;
    private javax.swing.JRadioButton rdbMasculinoMod;
    private javax.swing.JTextField txtNumMod;
    private javax.swing.JTextField txtRutBuscar;
    // End of variables declaration//GEN-END:variables
}
